version: "3"
services:
  ui: 
    depends_on:
      - api
    image: cloud.canister.io:5000/agronomo/gunship-escuela-alemana-ui-dev:latest
    ports:
      - "1337:80"
  api:
    ports:
    - "8080:80"
    image: cloud.canister.io:5000/agronomo/gunship-escuela-alemana-api-dev:latest
    depends_on:
      - db
  db:
    ports:
      - "5432:5432"
    image: cloud.canister.io:5000/agronomo/gunship-escuela-alemana-db-dev:latest
  pgadmin:
    ports:
      - "3333:80"
    depends_on:
      - db
    image: dpage/pgadmin4:5.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: school_admin@bar.aux
      PGADMIN_DEFAULT_PASSWORD: school
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

volumes:
#  db-data: # Too soon
  pgadmin-data:
